import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Next-ShadCN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en w-full min-h-screen h-full">
      <head />
      <body className="w-full h-full">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
